package store

import (
	"database/sql"
	"errors"
	"fmt"
	"math"
	"strconv"
	"strings"
)

// ErrVecUnavailable signals that the vec_chunks table doesn't exist yet — a
// vault not (re)embedded since the per-chunk vec0 index was introduced. Callers
// fall back to BM25 (or the doc-level brute-force path).
var ErrVecUnavailable = errors.New("vec_chunks table not available")

// ChunkVector is one chunk's embedding for a batch write into vec_chunks.
type ChunkVector struct {
	ChunkID     string
	DocID       string
	ContentHash string
	Vector      []float32
}

// ChunkScore is one vec0 KNN hit: the chunk, its document, and cosine similarity.
type ChunkScore struct {
	ChunkID string
	DocID   string
	Score   float64 // cosine similarity (1 - vec0 cosine distance)
}

// FiniteNonZero reports whether v is safe to store in a cosine-metric vec0
// index: every component is finite (no NaN/Inf) and at least one is non-zero.
// With distance_metric=cosine a zero-norm or NaN/Inf vector makes vec0 return a
// NULL distance, which sorts first under ORDER BY distance and (when scanned
// into a float64) aborts the entire KNN; vecLiteral would also emit invalid
// JSON (`NaN`/`+Inf`) that vec0 stores silently. Callers skip such vectors.
func FiniteNonZero(v []float32) bool {
	if len(v) == 0 {
		return false
	}
	nonZero := false
	for _, f := range v {
		f64 := float64(f)
		if math.IsNaN(f64) || math.IsInf(f64, 0) {
			return false
		}
		if f != 0 {
			nonZero = true
		}
	}
	return nonZero
}

// vecLiteral formats a vector as the sqlite-vec JSON array literal used to bind
// a query/insert vector (e.g. "[0.1,0.2,...]").
func vecLiteral(v []float32) string {
	var b strings.Builder
	b.Grow(len(v) * 9)
	b.WriteByte('[')
	for i, f := range v {
		if i > 0 {
			b.WriteByte(',')
		}
		b.WriteString(strconv.FormatFloat(float64(f), 'g', -1, 32))
	}
	b.WriteByte(']')
	return b.String()
}

// vecChunksDim returns the embedding dimension vec_chunks was created with, or 0
// if the table is absent.
func (db *DB) vecChunksDim() (int, error) {
	var ddl string
	err := db.conn.QueryRow(`SELECT sql FROM sqlite_master WHERE type='table' AND name='vec_chunks'`).Scan(&ddl)
	if errors.Is(err, sql.ErrNoRows) {
		return 0, nil
	}
	if err != nil {
		return 0, err
	}
	i := strings.Index(ddl, "float[")
	if i < 0 {
		return 0, nil
	}
	rest := ddl[i+len("float["):]
	j := strings.IndexByte(rest, ']')
	if j < 0 {
		return 0, nil
	}
	d, _ := strconv.Atoi(strings.TrimSpace(rest[:j]))
	return d, nil
}

// EnsureVecChunks makes the vec_chunks vec0 table match the active embedding
// dimension. vec0 fixes the dimension at table creation, so when the dimension
// changes (model switch / force-reembed) the table is dropped and recreated;
// the per-chunk embeddings are regenerated by the same index pass. doc_id /
// content_hash / model are auxiliary (+) columns so KNN returns the document
// without a join and re-embed gating can compare hashes.
func (db *DB) EnsureVecChunks(dim int) error {
	if dim <= 0 {
		return fmt.Errorf("invalid embedding dimension %d", dim)
	}
	// Serialize the check-then-create so concurrent embed workers (the parallel
	// re-embed pool) can't both create the table. The body is a fast metadata
	// read plus at most one DDL, so the lock is barely contended.
	db.ensureVecMu.Lock()
	defer db.ensureVecMu.Unlock()

	cur, err := db.vecChunksDim()
	if err != nil {
		return fmt.Errorf("inspect vec_chunks: %w", err)
	}
	if cur == dim {
		return nil
	}
	if cur != 0 {
		if _, err := db.conn.Exec(`DROP TABLE vec_chunks`); err != nil {
			return fmt.Errorf("drop stale vec_chunks (dim %d->%d): %w", cur, dim, err)
		}
	}
	// IF NOT EXISTS is belt-and-suspenders alongside the mutex: idempotent for a
	// redundant call and harmless if another process created it concurrently.
	_, err = db.conn.Exec(fmt.Sprintf(
		`CREATE VIRTUAL TABLE IF NOT EXISTS vec_chunks USING vec0(`+
			`chunk_id TEXT PRIMARY KEY, `+
			`embedding float[%d] distance_metric=cosine, `+
			`+doc_id TEXT, +content_hash TEXT, +model TEXT)`, dim))
	if err != nil {
		return fmt.Errorf("create vec_chunks[%d]: %w", dim, err)
	}
	return nil
}

// SetDocChunkVectors replaces all of a document's chunk vectors in vec_chunks
// (vec0 has no UPSERT, so it deletes the doc's rows then inserts). Call inside
// a doc's embedding step after EnsureVecChunks.
func (db *DB) SetDocChunkVectors(docID string, vectors []ChunkVector, model string) error {
	// Dedup by ChunkID, last occurrence wins (mirrors the chunks table's
	// ON CONFLICT(id) DO UPDATE), so colliding chunk IDs from duplicate heading
	// paths can't UNIQUE-fail the vec0 chunk_id PRIMARY KEY for an external
	// caller. embed.Document already dedups by content; this guards the API.
	keep := make(map[string]ChunkVector, len(vectors))
	order := make([]string, 0, len(vectors))
	for _, cv := range vectors {
		if _, seen := keep[cv.ChunkID]; !seen {
			order = append(order, cv.ChunkID)
		}
		keep[cv.ChunkID] = cv
	}

	if _, err := db.conn.Exec(`DELETE FROM vec_chunks WHERE doc_id = ?`, docID); err != nil {
		return fmt.Errorf("clear doc chunk vectors: %w", err)
	}
	for _, id := range order {
		cv := keep[id]
		// Skip a non-finite or zero-norm vector: a single degenerate chunk
		// embedding must not poison cosine KNN for the whole vault.
		if !FiniteNonZero(cv.Vector) {
			continue
		}
		if _, err := db.conn.Exec(
			`INSERT INTO vec_chunks(chunk_id, embedding, doc_id, content_hash, model) VALUES (?, ?, ?, ?, ?)`,
			cv.ChunkID, vecLiteral(cv.Vector), cv.DocID, cv.ContentHash, model,
		); err != nil {
			return fmt.Errorf("insert chunk vector %s: %w", cv.ChunkID, err)
		}
	}
	return nil
}

// DeleteDocChunkVectors removes a document's chunk vectors (no-op if vec_chunks
// is absent). Mirrors document deletes, since vec0 has no FK cascade.
func (db *DB) DeleteDocChunkVectors(docID string) error {
	if has, err := db.hasVecChunks(); err != nil || !has {
		return err
	}
	_, err := db.conn.Exec(`DELETE FROM vec_chunks WHERE doc_id = ?`, docID)
	return err
}

// VecSearchChunks runs a vec0 KNN over chunk vectors and returns the top-k
// chunks (with their document) whose cosine similarity is >= minScore. Returns
// ErrVecUnavailable when vec_chunks doesn't exist so the caller can fall back.
func (db *DB) VecSearchChunks(query []float32, k int, minScore float64) ([]ChunkScore, error) {
	has, err := db.hasVecChunks()
	if err != nil {
		return nil, err
	}
	if !has {
		return nil, ErrVecUnavailable
	}
	if k <= 0 {
		k = 20
	}
	rows, err := db.conn.Query(
		`SELECT chunk_id, doc_id, distance FROM vec_chunks WHERE embedding MATCH ? AND k = ? ORDER BY distance`,
		vecLiteral(query), k,
	)
	if err != nil {
		return nil, fmt.Errorf("vec0 knn: %w", err)
	}
	defer rows.Close()
	var out []ChunkScore
	for rows.Next() {
		var cs ChunkScore
		var dist sql.NullFloat64
		if err := rows.Scan(&cs.ChunkID, &cs.DocID, &dist); err != nil {
			return nil, fmt.Errorf("scan vec hit: %w", err)
		}
		if !dist.Valid {
			continue // NULL distance from a poisoned (zero-norm/NaN) stored row
		}
		cs.Score = 1 - dist.Float64 // cosine distance -> cosine similarity
		if minScore > 0 && cs.Score < minScore {
			continue
		}
		out = append(out, cs)
	}
	return out, rows.Err()
}

// ChunkVectorCount reports how many chunk vectors are stored (0 if absent).
func (db *DB) ChunkVectorCount() (int, error) {
	if has, err := db.hasVecChunks(); err != nil || !has {
		return 0, err
	}
	var n int
	err := db.conn.QueryRow(`SELECT count(*) FROM vec_chunks`).Scan(&n)
	return n, err
}

func (db *DB) hasVecChunks() (bool, error) {
	var name string
	err := db.conn.QueryRow(`SELECT name FROM sqlite_master WHERE type='table' AND name='vec_chunks'`).Scan(&name)
	if errors.Is(err, sql.ErrNoRows) {
		return false, nil
	}
	return err == nil, err
}
