package search

import (
	"database/sql"
	"fmt"
	"strings"
	"unicode"
)

type Result struct {
	DocID       string         `json:"doc_id"`
	Path        string         `json:"path"`
	Title       string         `json:"title"`
	ChunkID     string         `json:"chunk_id"`
	HeadingPath string         `json:"heading_path"`
	Content     string         `json:"content"`
	Score       float64        `json:"score"`
	// VectorScore is the raw cosine similarity when a result came through
	// the vector channel. Zero when the result is BM25-only. Lets callers
	// distinguish "strong semantic match" from "RRF scraped the barrel".
	VectorScore float64        `json:"vector_score,omitempty"`
	DocType     string         `json:"type"`
	Status      string         `json:"status"`
	Frontmatter map[string]any `json:"frontmatter,omitempty"`
}

type Options struct {
	Query    string
	Type     string
	Status   string
	Tag      string
	Limit    int
	BM25Only bool // force keyword-only search
	// MinVectorScore is the minimum cosine similarity for a vector hit to
	// count. Below this the vector channel ignores the doc so it doesn't
	// pad the RRF output with barely-related neighbors. Zero means "no
	// filter" — the caller should supply ai.AIConfig.ResolveSimilarityThreshold().
	MinVectorScore float64
}

// SearchMode indicates which search method was used.
type SearchMode string

const (
	ModeKeyword SearchMode = "keyword"
	ModeHybrid  SearchMode = "hybrid"
)

type Engine struct {
	db *sql.DB
}

func NewEngine(db *sql.DB) *Engine {
	return &Engine{db: db}
}

// Search performs a BM25 keyword search with structured filters.
func (e *Engine) Search(opts Options) ([]Result, error) {
	if opts.Limit <= 0 {
		opts.Limit = 20
	}

	if opts.Query == "" {
		return e.listByFilters(opts)
	}

	return e.bm25Search(opts)
}

// HybridSearch combines BM25 and vector search using Reciprocal Rank Fusion.
// queryEmbedding is the vector for the query text (generated by the caller).
// docIDs and embeddings are all document vectors from the store.
// Returns results and the search mode used.
func (e *Engine) HybridSearch(opts Options, queryEmbedding []float32, docIDs []string, embeddings [][]float32) ([]Result, SearchMode, error) {
	if opts.Limit <= 0 {
		opts.Limit = 20
	}

	if opts.Query == "" {
		results, err := e.listByFilters(opts)
		return results, ModeKeyword, err
	}

	// BM25 search
	bm25Results, err := e.bm25Search(opts)
	if err != nil {
		return nil, "", err
	}

	// If no embeddings or forced BM25-only, return keyword results
	if opts.BM25Only || len(embeddings) == 0 || queryEmbedding == nil {
		return bm25Results, ModeKeyword, nil
	}

	// Vector search, with optional threshold to drop noise neighbors
	vectorResults := VectorSearchThreshold(queryEmbedding, docIDs, embeddings, opts.Limit*2, opts.MinVectorScore)

	// Combine with RRF (engine implements DocLookup for vector-only results)
	combined := ReciprocalRankFusion(bm25Results, vectorResults, opts.Limit, e)
	return combined, ModeHybrid, nil
}

func (e *Engine) bm25Search(opts Options) ([]Result, error) {
	// Build the query with FTS5 BM25 ranking + joins for metadata filters
	query := `
		SELECT
			d.id, d.path, d.title, c.id, c.heading_path,
			snippet(chunks_fts, 0, '>>>','<<<', '...', 40),
			bm25(chunks_fts),
			d.doc_type, d.status, d.frontmatter
		FROM chunks_fts fts
		JOIN chunks c ON c.rowid = fts.rowid
		JOIN documents d ON d.id = c.doc_id
	`

	var conditions []string
	var args []any

	conditions = append(conditions, "chunks_fts MATCH ?")
	args = append(args, ftsQuery(opts.Query))

	if opts.Type != "" {
		conditions = append(conditions, "d.doc_type = ?")
		args = append(args, opts.Type)
	}
	if opts.Status != "" {
		conditions = append(conditions, "d.status = ?")
		args = append(args, opts.Status)
	}
	if opts.Tag != "" {
		conditions = append(conditions, "d.id IN (SELECT doc_id FROM tags WHERE tag = ?)")
		args = append(args, opts.Tag)
	}

	if len(conditions) > 0 {
		query += " WHERE " + strings.Join(conditions, " AND ")
	}

	query += " ORDER BY bm25(chunks_fts) LIMIT ?"
	args = append(args, opts.Limit)

	return e.executeSearch(query, args)
}

func (e *Engine) listByFilters(opts Options) ([]Result, error) {
	query := `
		SELECT
			d.id, d.path, d.title, '' as chunk_id, '' as heading_path,
			substr(d.frontmatter, 1, 200) as content,
			0.0 as score,
			d.doc_type, d.status, d.frontmatter
		FROM documents d
	`

	var conditions []string
	var args []any

	if opts.Type != "" {
		conditions = append(conditions, "d.doc_type = ?")
		args = append(args, opts.Type)
	}
	if opts.Status != "" {
		conditions = append(conditions, "d.status = ?")
		args = append(args, opts.Status)
	}
	if opts.Tag != "" {
		conditions = append(conditions, "d.id IN (SELECT doc_id FROM tags WHERE tag = ?)")
		args = append(args, opts.Tag)
	}

	if len(conditions) > 0 {
		query += " WHERE " + strings.Join(conditions, " AND ")
	}

	query += " ORDER BY d.modified_at DESC LIMIT ?"
	args = append(args, opts.Limit)

	return e.executeSearch(query, args)
}

func (e *Engine) executeSearch(query string, args []any) ([]Result, error) {
	rows, err := e.db.Query(query, args...)
	if err != nil {
		return nil, fmt.Errorf("search query: %w", err)
	}
	defer rows.Close()

	var results []Result
	for rows.Next() {
		var r Result
		var fmJSON string
		if err := rows.Scan(&r.DocID, &r.Path, &r.Title, &r.ChunkID, &r.HeadingPath,
			&r.Content, &r.Score, &r.DocType, &r.Status, &fmJSON); err != nil {
			return nil, fmt.Errorf("scan result: %w", err)
		}
		// Negate BM25 score (FTS5 returns negative, lower = better)
		if r.Score < 0 {
			r.Score = -r.Score
		}
		results = append(results, r)
	}

	return results, rows.Err()
}

// GetDocumentByID looks up a document's metadata for RRF vector-only results.
func (e *Engine) GetDocumentByID(id string) (Result, bool) {
	var r Result
	var fmJSON string
	err := e.db.QueryRow(`
		SELECT d.id, d.path, d.title, d.doc_type, d.status, d.frontmatter
		FROM documents d WHERE d.id = ?`, id).Scan(
		&r.DocID, &r.Path, &r.Title, &r.DocType, &r.Status, &fmJSON)
	if err != nil {
		return Result{}, false
	}
	return r, true
}

// questionWords are words that indicate natural language input vs keyword search.
var questionWords = map[string]bool{
	"what": true, "how": true, "why": true, "when": true, "where": true,
	"who": true, "which": true, "does": true, "do": true, "did": true,
	"can": true, "could": true, "should": true, "would": true,
}

// stopWords are filtered from FTS queries to improve matching.
var stopWords = map[string]bool{
	"is": true, "are": true, "was": true, "were": true, "the": true,
	"a": true, "an": true, "in": true, "on": true, "at": true,
	"to": true, "for": true, "of": true, "with": true, "and": true,
	"or": true, "not": true, "this": true, "that": true, "it": true,
	"its": true, "be": true, "been": true, "being": true, "have": true,
	"has": true, "had": true, "my": true, "your": true, "our": true,
	"their": true, "about": true, "between": true, "from": true,
}

// ftsQuery converts a query to FTS5 syntax.
// Natural language questions use OR; keyword queries use AND (H2 fix).
// Terms containing non-word characters (dots, dashes, slashes, colons)
// are wrapped in double quotes so FTS5 treats them as literal phrases
// instead of parsing them as column filters or other operators — without
// this, queries like "v0.1.9" or "claude-haiku-4-5" fail with a syntax
// error near "." or "-".
func ftsQuery(q string) string {
	words := strings.Fields(q)
	if len(words) == 0 {
		return q
	}

	// Detect if this looks like a natural language question
	isQuestion := false
	firstWord := strings.ToLower(strings.TrimRight(words[0], "?"))
	if questionWords[firstWord] || strings.HasSuffix(q, "?") {
		isQuestion = true
	}

	var parts []string
	for _, w := range words {
		w = strings.ReplaceAll(w, "\"", "")
		w = strings.ReplaceAll(w, "*", "")
		w = strings.TrimRight(w, "?!.,;:")
		w = strings.ToLower(w)
		if w == "" || stopWords[w] || questionWords[w] {
			continue
		}
		parts = append(parts, quoteForFTS(w))
	}
	if len(parts) == 0 {
		return strings.Join(strings.Fields(q), " ")
	}

	if isQuestion {
		return strings.Join(parts, " OR ")
	}
	// Keyword queries use implicit AND (space-separated = AND in FTS5)
	return strings.Join(parts, " ")
}

// quoteForFTS wraps a term in double quotes when it contains any character
// that isn't a letter, digit, or underscore. FTS5 parses unquoted terms
// through its query grammar, where punctuation like "." (column filter),
// "-" (NOT), "+" (AND), ":" (column separator) have operator meanings.
// Quoted terms are treated as literal phrases which the tokenizer then
// splits into tokens — giving us the "just search for this thing" behavior.
func quoteForFTS(term string) string {
	for _, r := range term {
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) && r != '_' {
			return "\"" + term + "\""
		}
	}
	return term
}
