package search

import (
	"database/sql"
	"encoding/json"
	"fmt"
	"log/slog"
	"strings"
	"unicode"
)

type Result struct {
	DocID       string  `json:"doc_id"`
	Path        string  `json:"path"`
	Title       string  `json:"title"`
	ChunkID     string  `json:"chunk_id"`
	HeadingPath string  `json:"heading_path"`
	Content     string  `json:"content"`
	Score       float64 `json:"score"`
	// VectorScore is the raw cosine similarity when a result came through
	// the vector channel. Zero when the result is BM25-only. Lets callers
	// distinguish "strong semantic match" from "RRF scraped the barrel".
	VectorScore float64        `json:"vector_score,omitempty"`
	DocType     string         `json:"type"`
	Status      string         `json:"status"`
	Frontmatter map[string]any `json:"frontmatter,omitempty"`
}

type Options struct {
	Query    string
	Type     string
	Status   string
	Tag      string
	Limit    int
	BM25Only bool // force keyword-only search
	// MinVectorScore is the minimum cosine similarity for a vector hit to
	// count. Below this the vector channel ignores the doc so it doesn't
	// pad the RRF output with barely-related neighbors. Zero means "no
	// filter" — the caller should supply ai.AIConfig.ResolveSimilarityThreshold().
	MinVectorScore float64
	// BM25Weight / VectorWeight bias the RRF fusion toward keyword or semantic
	// recall. Zero/non-positive means "unset" → 1.0 (classic equal-weight RRF).
	// Callers supply ai.AIConfig.ResolveHybridWeights().
	BM25Weight   float64
	VectorWeight float64
}

// SearchMode indicates which search method was used.
type SearchMode string

const (
	ModeKeyword SearchMode = "keyword"
	ModeHybrid  SearchMode = "hybrid"
)

type Engine struct {
	db *sql.DB
}

func NewEngine(db *sql.DB) *Engine {
	return &Engine{db: db}
}

// Search performs a BM25 keyword search with structured filters.
func (e *Engine) Search(opts Options) ([]Result, error) {
	if opts.Limit <= 0 {
		opts.Limit = 20
	}

	if opts.Query == "" {
		return e.listByFilters(opts)
	}

	return e.bm25Search(opts)
}

// HybridSearch combines BM25 and vector search using Reciprocal Rank Fusion.
// queryEmbedding is the vector for the query text (generated by the caller).
// docIDs and embeddings are all document vectors from the store.
// Returns results and the search mode used.
func (e *Engine) HybridSearch(opts Options, queryEmbedding []float32, docIDs []string, embeddings [][]float32) ([]Result, SearchMode, error) {
	if opts.Limit <= 0 {
		opts.Limit = 20
	}

	if opts.Query == "" {
		results, err := e.listByFilters(opts)
		return results, ModeKeyword, err
	}

	// BM25 search
	bm25Results, err := e.bm25Search(opts)
	if err != nil {
		return nil, "", err
	}

	if opts.BM25Only || queryEmbedding == nil {
		return bm25Results, ModeKeyword, nil
	}

	// Prefer the in-SQL per-chunk vec0 KNN (rolled up to best-per-doc): it
	// removes the Go-side embedding load and makes the vector signal per-chunk.
	// Fall back to the brute-force over whole-doc embeddings when the vec_chunks
	// table isn't present, or when it doesn't yet cover the whole corpus (a
	// vault only partially re-embedded under the vec0 index) — len(embeddings)
	// is the coverage target, since every embedded doc is in that corpus.
	// Both vector legs score on embeddings alone and know nothing about
	// doc_type, status or tags, so their candidates are filtered afterwards.
	// Over-fetch harder when a filter is active: the discard happens after the
	// KNN has already chosen its k, so a selective filter would otherwise starve
	// the result set.
	vecFetch := opts.Limit * 4
	if opts.hasFilters() {
		vecFetch = opts.Limit * 20
	}
	var vectorResults []ScoredDoc
	if vd, ok, verr := e.vecChunkSearchByDoc(queryEmbedding, vecFetch, opts.MinVectorScore, len(embeddings)); verr == nil && ok {
		vectorResults = vd
	} else if len(embeddings) > 0 {
		vectorResults = VectorSearchThreshold(queryEmbedding, docIDs, embeddings, vecFetch/2, opts.MinVectorScore)
	} else {
		return bm25Results, ModeKeyword, nil
	}

	// WITHOUT this the structured filters were silently discarded the moment RRF
	// merged an unfiltered vector hit in: `search --type adr` returned notes,
	// `--status accepted` returned drafts. Only the BM25 leg applied them, so
	// the bug appeared exactly when the semantic channel was healthy, which is
	// the default.
	vectorResults, err = e.filterScoredDocs(vectorResults, opts)
	if err != nil {
		return nil, "", err
	}

	// Combine with RRF (engine implements DocLookup for vector-only results)
	combined := ReciprocalRankFusion(bm25Results, vectorResults, opts.Limit, e, opts.BM25Weight, opts.VectorWeight)
	// Hydrate HERE, right after fusion, so every caller of HybridSearch (the
	// CLI search, ask, MCP kb_search, the eval harness) gets the same rows and
	// no surface has to know that a vector-only row arrives without its text.
	e.hydrateVectorOnly(combined)
	return combined, ModeHybrid, nil
}

// hydrateVectorOnly fills the snippet fields on rows that came ONLY from the
// vector leg, so a semantic hit carries its chunk's text exactly as a lexical
// hit does.
//
// ReciprocalRankFusion builds such a row from GetDocumentByID, which selects
// document metadata and no body at all, so `search --json` reported a hit with
// an empty `content` and every consumer that shows a snippet (the CLI, the
// macOS app, kb_search, the eval harness) showed nothing for exactly the
// results semantic search exists to find.
//
// Two shapes, because the two vector legs differ. The per-chunk vec0 KNN knows
// which chunk matched, so its row is filled from that chunk. The brute-force
// leg scores whole-document embeddings and knows no chunk, so its row takes the
// document's FIRST chunk, the same row listByFilters joins; that also gives it
// a ChunkID, which is what lets retrieve.candidateTexts backfill full text for
// the reranker on this leg too.
//
// Both cut the body with SQL substr, which counts CHARACTERS on a TEXT column,
// so the 200-unit snippet is rune-safe and byte-identical to the enumerated
// path's. store.ChunkContentByID is deliberately not reused: it returns up to
// 6000 runes, and parity with a lexical row wants 200. The SQL lives here for
// the same reason listByFilters' does: store/docs.go is watched by the
// index-generation gate, and nothing stored changes here.
//
// A note with no body has no chunks, so both queries OUTER-join and such a row
// keeps its empty Content rather than failing.
func (e *Engine) hydrateVectorOnly(results []Result) {
	byChunk := map[string]int{}
	byDoc := map[string][]int{}
	for i := range results {
		if results[i].Content != "" {
			continue
		}
		if id := results[i].ChunkID; id != "" {
			byChunk[id] = i
			continue
		}
		if id := results[i].DocID; id != "" {
			byDoc[id] = append(byDoc[id], i)
		}
	}
	if len(byChunk) > 0 {
		ids, placeholders := queryKeys(byChunk)
		rows, err := e.db.Query(`
			SELECT id, COALESCE(heading_path, ''), COALESCE(substr(content, 1, 200), '')
			FROM chunks WHERE id IN (`+placeholders+`)`, ids...)
		if err == nil {
			for rows.Next() {
				var id, heading, content string
				if err := rows.Scan(&id, &heading, &content); err != nil {
					break
				}
				i, ok := byChunk[id]
				if !ok {
					continue
				}
				results[i].Content = content
				if results[i].HeadingPath == "" {
					results[i].HeadingPath = heading
				}
			}
			rows.Close()
		}
	}
	if len(byDoc) > 0 {
		ids, placeholders := queryKeys(byDoc)
		rows, err := e.db.Query(`
			SELECT d.id,
			       COALESCE(c.id, ''),
			       COALESCE(c.heading_path, ''),
			       COALESCE(substr(c.content, 1, 200), '')
			FROM documents d
			LEFT JOIN chunks c ON c.id = (
				SELECT c2.id FROM chunks c2
				WHERE c2.doc_id = d.id
				ORDER BY c2.sort_order, c2.start_line, c2.id
				LIMIT 1
			)
			WHERE d.id IN (`+placeholders+`)`, ids...)
		if err == nil {
			for rows.Next() {
				var docID, chunkID, heading, content string
				if err := rows.Scan(&docID, &chunkID, &heading, &content); err != nil {
					break
				}
				for _, i := range byDoc[docID] {
					results[i].Content = content
					if results[i].ChunkID == "" {
						results[i].ChunkID = chunkID
					}
					if results[i].HeadingPath == "" {
						results[i].HeadingPath = heading
					}
				}
			}
			rows.Close()
		}
	}
}

// queryKeys renders a map's keys as query arguments plus the matching `?,?`
// placeholder list, so an IN clause is always parameterized and never built by
// interpolating identifiers.
func queryKeys[V any](m map[string]V) ([]any, string) {
	args := make([]any, 0, len(m))
	ph := make([]string, 0, len(m))
	for k := range m {
		args = append(args, k)
		ph = append(ph, "?")
	}
	return args, strings.Join(ph, ",")
}

// hasFilters reports whether any structured filter is set.
func (o Options) hasFilters() bool {
	return o.Type != "" || o.Status != "" || o.Tag != ""
}

// filterConditions renders the structured filters as SQL against a documents
// alias of `d`. One definition for all three readers (the BM25 leg, the
// query-less listing, and the vector-candidate filter), because three copies is
// how the vector leg came to disagree with the BM25 leg in the first place.
func (o Options) filterConditions() ([]string, []any) {
	var conditions []string
	var args []any
	if o.Type != "" {
		conditions = append(conditions, "d.doc_type = ?")
		args = append(args, o.Type)
	}
	if o.Status != "" {
		conditions = append(conditions, "d.status = ?")
		args = append(args, o.Status)
	}
	if o.Tag != "" {
		conditions = append(conditions, "d.id IN (SELECT doc_id FROM tags WHERE tag = ?)")
		args = append(args, o.Tag)
	}
	return conditions, args
}

// filterScoredDocs drops vector candidates whose document does not satisfy the
// structured filters, so the vector leg honors --type/--status/--tag exactly
// like the BM25 leg does. One query, so a large candidate pool costs one round
// trip rather than one per document.
func (e *Engine) filterScoredDocs(docs []ScoredDoc, opts Options) ([]ScoredDoc, error) {
	if len(docs) == 0 || !opts.hasFilters() {
		return docs, nil
	}
	placeholders := make([]string, len(docs))
	args := make([]any, 0, len(docs)+3)
	for i, d := range docs {
		placeholders[i] = "?"
		args = append(args, d.DocID)
	}
	query := "SELECT d.id FROM documents d WHERE d.id IN (" + strings.Join(placeholders, ",") + ")"
	conditions, filterArgs := opts.filterConditions()
	for _, c := range conditions {
		query += " AND " + c
	}
	args = append(args, filterArgs...)
	rows, err := e.db.Query(query, args...)
	if err != nil {
		return nil, fmt.Errorf("filter vector candidates: %w", err)
	}
	defer rows.Close()
	allowed := make(map[string]bool, len(docs))
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		allowed[id] = true
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	kept := make([]ScoredDoc, 0, len(docs))
	for _, d := range docs {
		if allowed[d.DocID] {
			kept = append(kept, d)
		}
	}
	if len(kept) == 0 {
		// Not a user-facing warning: a filter excluding every semantic candidate
		// is the filter working, and a line on every such query would be noise on
		// the common `search --type adr` path. Debug-level so a "why did semantic
		// ranking stop contributing?" question is answerable from cli.log.
		slog.Debug("search: structured filters discarded every vector candidate",
			"candidates", len(docs), "type", opts.Type, "status", opts.Status, "tag", opts.Tag)
	}
	return kept, nil
}

func (e *Engine) bm25Search(opts Options) ([]Result, error) {
	// Build the query with FTS5 BM25 ranking + joins for metadata filters
	query := `
		SELECT
			d.id, d.path, d.title, c.id, c.heading_path,
			snippet(chunks_fts, 0, '>>>','<<<', '...', 40),
			bm25(chunks_fts),
			d.doc_type, d.status, d.frontmatter
		FROM chunks_fts fts
		JOIN chunks c ON c.rowid = fts.rowid
		JOIN documents d ON d.id = c.doc_id
	`

	var conditions []string
	var args []any

	conditions = append(conditions, "chunks_fts MATCH ?")
	args = append(args, ftsQuery(opts.Query))

	filterConds, filterArgs := opts.filterConditions()
	conditions = append(conditions, filterConds...)
	args = append(args, filterArgs...)

	if len(conditions) > 0 {
		query += " WHERE " + strings.Join(conditions, " AND ")
	}

	query += " ORDER BY bm25(chunks_fts) LIMIT ?"
	args = append(args, opts.Limit)

	return e.executeSearch(query, args)
}

func (e *Engine) listByFilters(opts Options) ([]Result, error) {
	// A blank query with a filter (`search "type:adr"`) enumerates documents,
	// and it used to fill the shared 10-column scan with `'' as chunk_id, ''
	// as heading_path, substr(d.frontmatter, 1, 200) as content`. So an
	// enumerated row's "content" was the note's frontmatter JSON, not its
	// prose, and every consumer that pins a result by chunk (the reranker's
	// text backfill among them) had nothing to pin.
	//
	// `documents` carries no body column; the only body text in the index is
	// chunks.content. Join the document's FIRST chunk: ordered by sort_order,
	// then start_line, then id, because split sub-chunks share their parent's
	// sort_order. It must be an OUTER join, since a body-less note has no
	// chunks at all, and every joined column is COALESCEd because the scan
	// targets are plain strings, not sql.NullString.
	//
	// The SQL lives here rather than in store/docs.go on purpose: docs.go is a
	// watched file for the index-generation gate, and nothing stored changes
	// here, so no reindex is needed.
	query := `
		SELECT
			d.id, d.path, d.title,
			COALESCE(c.id, '') as chunk_id,
			COALESCE(c.heading_path, '') as heading_path,
			COALESCE(substr(c.content, 1, 200), '') as content,
			0.0 as score,
			d.doc_type, d.status, d.frontmatter
		FROM documents d
		LEFT JOIN chunks c ON c.id = (
			SELECT c2.id FROM chunks c2
			WHERE c2.doc_id = d.id
			ORDER BY c2.sort_order, c2.start_line, c2.id
			LIMIT 1
		)
	`

	conditions, args := opts.filterConditions()

	if len(conditions) > 0 {
		query += " WHERE " + strings.Join(conditions, " AND ")
	}

	query += " ORDER BY d.modified_at DESC LIMIT ?"
	args = append(args, opts.Limit)

	return e.executeSearch(query, args)
}

func (e *Engine) executeSearch(query string, args []any) ([]Result, error) {
	rows, err := e.db.Query(query, args...)
	if err != nil {
		return nil, fmt.Errorf("search query: %w", err)
	}
	defer rows.Close()

	var results []Result
	for rows.Next() {
		var r Result
		var fmJSON string
		if err := rows.Scan(&r.DocID, &r.Path, &r.Title, &r.ChunkID, &r.HeadingPath,
			&r.Content, &r.Score, &r.DocType, &r.Status, &fmJSON); err != nil {
			return nil, fmt.Errorf("scan result: %w", err)
		}
		r.Frontmatter = decodeFrontmatter(fmJSON)
		// Negate BM25 score (FTS5 returns negative, lower = better)
		if r.Score < 0 {
			r.Score = -r.Score
		}
		results = append(results, r)
	}

	return results, rows.Err()
}

// GetDocumentByID looks up a document's metadata for RRF vector-only results.
func (e *Engine) GetDocumentByID(id string) (Result, bool) {
	var r Result
	var fmJSON string
	err := e.db.QueryRow(`
		SELECT d.id, d.path, d.title, d.doc_type, d.status, d.frontmatter
		FROM documents d WHERE d.id = ?`, id).Scan(
		&r.DocID, &r.Path, &r.Title, &r.DocType, &r.Status, &fmJSON)
	if err != nil {
		return Result{}, false
	}
	r.Frontmatter = decodeFrontmatter(fmJSON)
	return r, true
}

// decodeFrontmatter turns a documents.frontmatter cell into the map every
// Result carries. Both scan sites call it, so BM25, enumerated, and vector-only
// rows agree about the field; it had been scanned into a local and thrown away
// at both, which left Result.Frontmatter dead since the first commit and made
// csv/tsv render every row's frontmatter column as the Go rendering of a nil
// map. A malformed cell yields an empty map rather than an error, matching
// store.GetDocumentByPath.
func decodeFrontmatter(fmJSON string) map[string]any {
	var out map[string]any
	if err := json.Unmarshal([]byte(fmJSON), &out); err != nil {
		return map[string]any{}
	}
	return out
}

// questionWords are words that indicate natural language input vs keyword search.
var questionWords = map[string]bool{
	"what": true, "how": true, "why": true, "when": true, "where": true,
	"who": true, "which": true, "does": true, "do": true, "did": true,
	"can": true, "could": true, "should": true, "would": true,
}

// stopWords are filtered from FTS queries to improve matching.
var stopWords = map[string]bool{
	"is": true, "are": true, "was": true, "were": true, "the": true,
	"a": true, "an": true, "in": true, "on": true, "at": true,
	"to": true, "for": true, "of": true, "with": true, "and": true,
	"or": true, "not": true, "this": true, "that": true, "it": true,
	"its": true, "be": true, "been": true, "being": true, "have": true,
	"has": true, "had": true, "my": true, "your": true, "our": true,
	"their": true, "about": true, "between": true, "from": true,
}

// ftsQuery converts a query to FTS5 syntax.
// Natural language questions use OR; keyword queries use AND (H2 fix).
// Terms containing non-word characters (dots, dashes, slashes, colons)
// are wrapped in double quotes so FTS5 treats them as literal phrases
// instead of parsing them as column filters or other operators — without
// this, queries like "v0.1.9" or "claude-haiku-4-5" fail with a syntax
// error near "." or "-".
func ftsQuery(q string) string {
	words := strings.Fields(q)
	if len(words) == 0 {
		return q
	}

	// Detect if this looks like a natural language question
	isQuestion := false
	firstWord := strings.ToLower(strings.TrimRight(words[0], "?"))
	if questionWords[firstWord] || strings.HasSuffix(q, "?") {
		isQuestion = true
	}

	var parts []string
	for _, w := range words {
		w = strings.ReplaceAll(w, "\"", "")
		w = strings.ReplaceAll(w, "*", "")
		w = strings.TrimRight(w, "?!.,;:")
		w = strings.ToLower(w)
		if w == "" || stopWords[w] || questionWords[w] {
			continue
		}
		parts = append(parts, quoteForFTS(w))
	}
	if len(parts) == 0 {
		return strings.Join(strings.Fields(q), " ")
	}

	if isQuestion {
		return strings.Join(parts, " OR ")
	}
	// Keyword queries use implicit AND (space-separated = AND in FTS5)
	return strings.Join(parts, " ")
}

// quoteForFTS wraps a term in double quotes when it contains any character
// that isn't a letter, digit, or underscore. FTS5 parses unquoted terms
// through its query grammar, where punctuation like "." (column filter),
// "-" (NOT), "+" (AND), ":" (column separator) have operator meanings.
// Quoted terms are treated as literal phrases which the tokenizer then
// splits into tokens — giving us the "just search for this thing" behavior.
func quoteForFTS(term string) string {
	for _, r := range term {
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) && r != '_' {
			return "\"" + term + "\""
		}
	}
	return term
}
